openapi: 3.0.1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/trates/{id}/{price}:
    put:
      tags:
      - trates-rest
      operationId: updateTrates
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: price
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trates'
  /api/trates/:
    get:
      tags:
      - trates-rest
      operationId: listAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trates'
    post:
      tags:
      - trates-rest
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trates'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trates'
  /api/trates/{id}:
    get:
      tags:
      - trates-rest
      operationId: tratesForId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FormatedTrates'
    delete:
      tags:
      - trates-rest
      operationId: deleteTratesById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/trates/{date}/{product_id}/{brand_id}:
    get:
      tags:
      - trates-rest
      operationId: findTratesDateIdProductIdBrand
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: brand_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormatedTrates'
  /api/trates/hello:
    get:
      tags:
      - trates-rest
      operationId: showHello
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Trates:
      type: object
      properties:
        id:
          type: integer
          format: int32
        brand_id:
          type: integer
          format: int32
        product_id:
          type: integer
          format: int32
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        price:
          type: integer
          format: int32
        currency_code:
          type: string
    FormatedTrates:
      type: object
      properties:
        id:
          type: integer
          format: int32
        brand_id:
          type: integer
          format: int32
        product_id:
          type: integer
          format: int32
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        price:
          type: string
        currency_code:
          type: string
